version: "3.7"

services:
  project_manager:
    build: ./project_manager
    container_name: 'project_manager'
    restart: always
    env_file:
      - project_manager/.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /host:/app/data/media
      - /host:/app/data/database
    ports:
      - '8000'

  nginx:
    build: ./nginx
    container_name: 'projects_nginx'
    restart: always
    depends_on:
      - project_manager
    volumes:
      - /host:/app/media
    ports:
      - "80:80"

