# Generated by Django 4.1.5 on 2023-01-28 10:17

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenationnotefilestorage',
            name='file',
            field=models.FileField(upload_to='', validators=[projects.validators.check_file_size]),
        ),
        migrations.AlterField(
            model_name='projectfilestorage',
            name='file',
            field=models.FileField(upload_to='', validators=[projects.validators.check_file_size]),
        ),
        migrations.AlterField(
            model_name='taskeventfilestorage',
            name='file',
            field=models.FileField(upload_to='', validators=[projects.validators.check_file_size]),
        ),
        migrations.AlterField(
            model_name='taskfilestorage',
            name='file',
            field=models.FileField(upload_to='', validators=[projects.validators.check_file_size]),
        ),
    ]
