# Generated by Django 4.1.5 on 2023-01-28 10:34

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_documenationnotefilestorage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenationnotefilestorage',
            name='file',
            field=models.FileField(upload_to='documentation_notes/%Y/%m/%d/', validators=[projects.validators.check_file_size]),
        ),
        migrations.AlterField(
            model_name='projectfilestorage',
            name='file',
            field=models.FileField(upload_to='projects/%Y/%m/%d/', validators=[projects.validators.check_file_size]),
        ),
        migrations.AlterField(
            model_name='taskeventfilestorage',
            name='file',
            field=models.FileField(upload_to='task_events/%Y/%m/%d/', validators=[projects.validators.check_file_size]),
        ),
        migrations.AlterField(
            model_name='taskfilestorage',
            name='file',
            field=models.FileField(upload_to='tasks/%Y/%m/%d/', validators=[projects.validators.check_file_size]),
        ),
    ]
