# Generated by Django 4.1.1 on 2023-04-15 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectdocumentationnote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocumentationnote',
            name='documentation',
        ),
        migrations.AddField(
            model_name='projectdocumentationnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdocumentationnote',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdocumentationnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
