# Generated by Django 4.1.1 on 2023-04-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectfilestorage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdocumentationnote',
            options={'verbose_name': 'Запись проекта', 'verbose_name_plural': 'Записи проектов'},
        ),
        migrations.AlterModelTable(
            name='projectdocumentationnote',
            table='project_notes',
        ),
    ]
